version: '3.8'

services:
  mediawiki:
    image: nv-wiki
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 500M
    networks:
      - servernet
      - internal
      - monitor-net
    depends_on:
      - database
    volumes:
      # Does not contain important data,
      # used by MediaWiki to keep track of database schema upgrades.
      - smw-config:/data/smw-config
    secrets:
      - wiki-password
      - aws-credentials
      - discord-auth-client-secret
      - discord-auth-bot-token
      - wg-secret
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=servernet"
      - "traefik.http.routers.mediawiki.rule=Host(`nv-intl.com`) || Host(`www.nv-intl.com`)"
      - "traefik.http.routers.mediawiki.middlewares=mediawiki-stripprefix"
      # Backwards compatibility with old URLs
      - "traefik.http.middlewares.mediawiki-stripprefix.stripprefix.prefixes=/wiki"
      - "traefik.http.services.mediawiki.loadbalancer.server.port=80"
      - "traefik.http.routers.mediawiki.entrypoints=websecure"
      - "traefik.http.routers.mediawiki.tls.certresolver=myresolver"
  database:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal
  database-backup:
    image: nv-wiki-db-backup
    depends_on:
      - database
    networks:
      - internal
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/database-backup-aws-credentials
    secrets:
      - database-backup-aws-credentials
      - wiki-password
    deploy:
      restart_policy:
        condition: any
        delay: 24h

volumes:
  db:
  smw-config:

networks:
  internal:
    driver: overlay
  servernet:
    external: true
  monitor-net:
    external: true

secrets:
  # AWS credentials file for a user with s3:PutObject permission
  # on arn:aws:s3:::night-vision-wiki-backups/*
  database-backup-aws-credentials:
    external: true
    name: nv-wiki-db-backup-aws-credentials
  # Password for the database user 'wiki'
  wiki-password:
    external: true
    name: wiki-password
  # AWS credentials file for a user with permissions according to 
  # https://www.mediawiki.org/wiki/Extension:AWS#Configuration
  # on the bucket night-vision-wiki
  aws-credentials:
    external: true
    name: nv-wiki-aws-credentials
  # Discord App Client Secret, see
  # https://github.com/markusa380/mediawiki-DiscordAuth/blob/REL1_40/README.md#localsettingsphp-minimal-setup
  discord-auth-client-secret:
    external: true
    name: nv-wiki-discord-auth-client-secret
  # Discord Bot Token, see
  # https://github.com/markusa380/mediawiki-DiscordAuth/blob/REL1_40/README.md#localsettingsphp-minimal-setup
  discord-auth-bot-token:
    external: true
    name: nv-wiki-discord-auth-bot-token
  # See https://www.mediawiki.org/wiki/Manual:$wgSecretKey
  wg-secret:
    external: true
    name: nv-wiki-wg-secret